=== raullopeslopez/LL.MM_Actividad2/biblioteca.dtd
<!-- Nodos raÃ­z-->

<!ELEMENT biblioteca (libros+,revistas+,periodicos+)> 
<!ELEMENT libros (libro+)>
<!ELEMENT revistas (revista+)>
<!ELEMENT periodicos (periodico+)>

<!-- Elemento Libro -->

<!ELEMENT libro (titulo_lib,capitulos_lib)>
<!ATTLIST libro
    id_libro ID #REQUIRED
    tipo_clase CDATA #REQUIRED
    pags_libro CDATA #REQUIRED>
<!ELEMENT titulo_lib (#PCDATA)>
<!ELEMENT capitulos_lib (capitulo_lib+)>
<!ELEMENT capitulo_lib (titulo_cap,contenido_cap,indice_cap,sinopsis)>
<!ATTLIST capitulo_lib
    pags_capitulo CDATA #REQUIRED>
<!ELEMENT titulo_cap (#PCDATA)>
<!ELEMENT contenido_cap (#PCDATA)>
<!ATTLIST contenido_cap
  enlace CDATA #REQUIRED>  
<!ELEMENT indice_cap (#PCDATA)> 
<!ELEMENT sinopsis (#PCDATA)>

<!-- Elemento Revista -->


<!ELEMENT revista (titulo_rev, num_revista, ind_revista, secciones_rev)>
<!ATTLIST revista
    id_revista ID #REQUIRED
    tipo_clase CDATA #REQUIRED
    pags_revista CDATA #REQUIRED>
<!ELEMENT titulo_rev (#PCDATA)>
<!ELEMENT num_revista (#PCDATA)>
<!ELEMENT ind_revista (#PCDATA)>
<!ELEMENT secciones_rev (seccion_rev+)>
<!ELEMENT seccion_rev (contenido_rev)>
<!ATTLIST seccion_rev 
    pags_revista CDATA #REQUIRED>
<!ELEMENT contenido_rev (#PCDATA)>
<!ATTLIST contenido_rev
  enlace CDATA #REQUIRED>


<!-- Elemento Periodico -->

<!ELEMENT periodico (indice_per,secciones_per+)>
<!ATTLIST periodico
    id_periodico ID #REQUIRED
    tipo_clase CDATA #REQUIRED
    fecha_pub CDATA #REQUIRED>  
<!ELEMENT indice_per (#PCDATA)>
<!ELEMENT secciones_per (seccion_per+)>
<!ELEMENT seccion_per (articulos_per)>
<!ATTLIST seccion_per
    id_seccion ID #REQUIRED>
<!ELEMENT articulos_per (articulo_per+,contenido_art)>
<!ELEMENT articulo_per (#PCDATA)>
<!ATTLIST articulo_per
    autor CDATA #REQUIRED>
<!ELEMENT contenido_art (#PCDATA)>
<!ATTLIST contenido_art
  enlace CDATA #REQUIRED>

=== raullopeslopez/LL.MM_Actividad2/Raúl/biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libros>
        <libro id_libro= "L1234" tipo_clase="Novela" pags_libro= "356">
            <titulo_lib>Titulo libro</titulo_lib>
            <capitulos_lib>
                <capitulo_lib pags_capitulo= "23">
                    <titulo_cap>Capitulo 2</titulo_cap>
                    <contenido_cap enlace= "Enlace a informacion"></contenido_cap>
                    <indice_cap></indice_cap>
                    <sinopsis></sinopsis>
                </capitulo_lib>
            </capitulos_lib>
        </libro>
    </libros>
    <revistas>
        <revista id_revista= "R1234" tipo_clase="Informatica" pags_revista= "27">
            <titulo_rev>Titulo revista</titulo_rev>
            <num_revista></num_revista>
            <ind_revista></ind_revista>
            <secciones_rev>
                <seccion_rev pags_revista= "3">
                    <contenido_rev enlace= "Enlace a informacion"></contenido_rev>
                </seccion_rev>
            </secciones_rev>  
        </revista>
    </revistas> 
    <periodicos>
        <periodico id_periodico= "P1234" tipo_clase="Internacional" fecha_pub= "x/x/x"> 
            <indice_per></indice_per>
            <secciones_per>
                <seccion_per id_seccion= "Economia">
                    <articulos_per>
                        <articulo_per autor= "J. R. Rallo"></articulo_per>
                        <contenido_art enlace= "Enlace a contenido"></contenido_art>
                    </articulos_per>
                </seccion_per>
            </secciones_per>
        </periodico>
    </periodicos>    
</biblioteca>
