=== raullopeslopez/LL.MM_Actividad2/Jorge/biblioteca.dtd
<!-- Nodos -->

<!ELEMENT biblioteca (libros+,revistas+,periodicos+)> 
<!ELEMENT libros (libro+)>
<!ELEMENT revistas (revista+)>
<!ELEMENT periodicos (periodico+)>

<!-- Libros -->

<!ELEMENT libro (titulo,capitulos,indice,sinopsis)>
<!ATTLIST libro
    id ID #REQUIRED
    tipo_clase CDATA #REQUIRED
    paginas CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (contenido)>
<!ATTLIST capitulo
    paginas CDATA #REQUIRED>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido
  enlace CDATA #REQUIRED>  
<!ELEMENT sinopsis (#PCDATA)>

<!-- Revistas -->


<!ELEMENT revista (titulo, numero_revista, indice, secciones)>
<!ATTLIST revista
    id ID #REQUIRED
    tipo_clase CDATA #REQUIRED>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT ind_revista (#PCDATA)>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (contenido)>
<!ATTLIST seccion 
    paginas CDATA #REQUIRED>
<!ATTLIST contenido
  enlace CDATA #REQUIRED>


<!-- Periodicos -->

<!ELEMENT periodico (seciones+, indice)>
<!ATTLIST periodico
    id ID #REQUIRED
    tipo_clase CDATA #REQUIRED
    fecha CDATA #REQUIRED>  
<!ELEMENT seciones (articulo+)>
<!ATTLIST seciones
    tipo_seccion CDATA #REQUIRED>
<!ELEMENT articulo (contenido)>
<!ATTLIST articulo
    autor CDATA #REQUIRED>
<!ATTLIST contenido
  enlace CDATA #REQUIRED>

=== raullopeslopez/LL.MM_Actividad2/Jorge/biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
	<libros>
		<libro id="L1234" tipo_clase = "novela" paginas = "40">
			<titulo>Título</titulo>
			<capitulos>
				<capitulo paginas = "10">
					<contenido enlace = ""></contenido>
				</capitulo>
				<capitulo paginas = "10">
					<contenido enlace = ""></contenido>
				</capitulo>
				<capitulo paginas = "10">
					<contenido enlace = ""></contenido>
				</capitulo>
				<capitulo paginas = "10">
					<contenido enlace = ""></contenido>
				</capitulo>	
			</capitulos>
			<indice>Índice</indice>
			<sinopsis>Sinopsis</sinopsis>
		</libro>
	</libros>
	<revistas>
		<revista id="R1234" tipo_clase = "informatica">
			<titulo>Título</titulo>
			<numero_revista>6</numero_revista>
			<indice>Índice</indice>
			<secciones>
				<seccion paginas = "10">
					<contenido enlace = ""></contenido>
				</seccion>
				<seccion paginas = "10">
					<contenido enlace = ""></contenido>
				</seccion>
				<seccion paginas = "10">
					<contenido enlace = ""></contenido>
				</seccion>
			</secciones>
		</revista>
	</revistas>
	<periodicos>
		<periodico id="P1234" tipo_clase = "nacional" fecha = "20/02/2020">
			<seccionesP tipo_seccion = "economica">
				<articulo autor ="Juan">
					<contenido enlace = ""></contenido>
				</articulo>
				<articulo autor ="Maria">
					<contenido enlace = ""></contenido>
				</articulo>
				<articulo autor ="Pepe">
					<contenido enlace = ""></contenido>
				</articulo>
			</seccionesP>
			<indice>Índice</indice>
		</periodico>
	</periodicos>
</biblioteca>

=== raullopeslopez/LL.MM_Actividad2/Adrian/Biblioteca v.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "Biblioteca.dtd">

<biblioteca>
    <libros>
        <libro id="L9251" num_paginas="118" tipo_clase="novela">
            <indice> Capitulo uno</indice>
                <capitulos titulo="Cap VII: El experimento">
                    <capitulo cap_paginas="17">
						<contenido contenido="https://www.amazon.es/tejedora-muerte-Castellano-Partir-Altamar/dp/8421652524%22%3E"></contenido>
					</capitulo>
				</capitulos>
            <titulo>La tejedora</titulo>
            <sinopsis>Narra la historia de una mujer que al regresar a su antigua casa comienza a recordar sucesos de su pasado...</sinopsis>

        </libro>
    </libros>
    <revistas>
            <revista id="R5987" tipo_clase="investigacion" secciones="7">
                <secciones_revista num_paginas="7">
                    <seccion_revista contenido="https://www.soundonsound.com/%22%3E">
						<contenido>Contenido</contenido>
					</seccion_revista>
                </secciones_revista>
                <titulo>SOS</titulo>
                <num_revista>87</num_revista>
                <indice>La física del sonido...</indice>
            </revista>
    </revistas>
    <periodicos>
            <periodico id="P6553" tipo_clase="nacionales" f_publicacion="11/07/2010">
                <secciones>
                    <seccion tipo_seccion="deportes">
                        <articulos autor="Álvaro Roca">Uno</articulos>
                    </seccion>
                </secciones>
                <indice>Somos campeones del mundo...</indice>
        </periodico>
    </periodicos>
</biblioteca>
